# Generated by Django 2.2.5 on 2021-03-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210302_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'email'), ('github', 'github'), ('kakao', 'kakao')], default='email', max_length=50),
        ),
    ]
